name: ${artifactId}
main: com.github.Cnly.BReplacer.BReplacer.Main
version: ${version}
author: Cnly

commands:
  brp:
    description: The main command of BReplacer.
    usage: /brp to replace the plugins specified in config.yml and reload the server.
